steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/first-cluster-461402/first-cluster-registry/codefresh-node-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/first-cluster-461402/first-cluster-registry/codefresh-node-app:latest']

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east1'  
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster1'
    args: ['apply', '-f', 'k8s-manifests/']  
