steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-east1-docker.pkg.dev/codefresh-project-123/codefresh-repo/codefresh-node-app:latest',
      '.'
    ]

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east1-docker.pkg.dev/codefresh-project-123/codefresh-repo/codefresh-node-app:latest'
    ]

  # Step 3: Set kubectl context (auth to GKE)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials codefresh-cluster --zone us-east1-b --project codefresh-project-123 &&
        kubectl apply -f k8s-manifests/

# Set substitutions if you want reusable variables (optional)
substitutions:
  _IMAGE_NAME: codefresh-node-app
  _REGION: us-east1


