apiVersion: apps/v1
kind: Deployment
metadata:
  name: codefresh-node-app
  labels:
    app: codefresh-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codefresh-node-app
  template:
    metadata:
      labels:
        app: codefresh-node-app
    spec:
      containers:
        - name: app
          image: us-east1-docker.pkg.dev/codefresh-project-123/codefresh-repo/codefresh-node-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: artifact-registry-secret
