apiVersion: apps/v1
kind: Deployment
metadata:
  name: codefresh-node-app
  labels:
    app: codefresh-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codefresh-node-app
  template:
    metadata:
      labels:
        app: codefresh-node-app
    spec:
      containers:
      - name: app
        image: codefresh-node-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"