apiVersion: apps/v1
kind: Deployment
metadata:
  name: codefresh-node-app
  labels:
    app: codefresh-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codefresh-node-app
  template:
    metadata:
      labels:
        app: codefresh-node-app
    spec:
      containers:
      - name: app
        image: us-east1-docker.pkg.dev/first-cluster-461402/first-cluster-registry/codefresh-node-app@sha256:5bf1ec57a74024e6408b2d99b93be9634eaa4c47cf34e0dfd3b021b20430af5e
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"