apiVersion: v1
kind: Service
metadata:
  name: codefresh-node-app-service
spec:
  selector:
    app: codefresh-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
